
mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
ipv6: true
log-level: info
external-controller: '127.0.0.1:9090'

dns:
  enabled: true
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - https://dns.alidns.com/dns-query # 阿里 DoH DNS
    - https://doh.360.cn/dns-query # 360 DoH DNS
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://cloudflare-dns.com/dns-query

cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204
